#!/bin/bash

CAMPAIGNS=""
#CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL16wmLHEGEN"
#CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL16wmLHEGENAPV"
#CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL17wmLHEGEN"
#CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL18wmLHEGEN"
#CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL16GEN"
CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL16GENAPV"
#CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL17GEN"
#CAMPAIGNS=$CAMPAIGNS" RunIISummer19UL18GEN"
#CAMPAIGNS=$CAMPAIGNS" Run3Summer19GS"
#CAMPAIGNS=$CAMPAIGNS" Run3Summer19wmLHEGS"
#CAMPAIGNS=$CAMPAIGNS" Run3Winter20GS"
#CAMPAIGNS=$CAMPAIGNS" Run3Winter20wmLHEGS"

python listRequests.py --notDev --verbose $1 --campaigns $CAMPAIGNS
